In [2]:
import numpy as np

In [11]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
z=np.zeros((3,3))
z[1,:]=5
z[:,2]=7
print(z[1:3,1:])

[[5. 7.]
 [0. 7.]]


In [19]:
b=np.full((2,3),5,dtype=np.float64)
print(b)

[[5. 5. 5.]
 [5. 5. 5.]]


In [3]:
j=np.eye(6)
j=j**2
print(j)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [5]:
#random Matrix
randommatrix=np.random.random((2,3))
print(randommatrix[:,1])

[0.99230811 0.81144518]


In [8]:
x=np.zeros((3,3))
print(x.dtype)
print(x)

float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
x=np.zeros((3,3),dtype=np.int64)
print(x.dtype)
print(x)

int64
[[0 0 0]
 [0 0 0]
 [0 0 0]]


MATHEMATICAL OPERATIONS

In [23]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [21]:
#elemental operations
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [25]:
#matrix multiplaication/scalar multiplication
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
#Dot product of Vectors
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))

30


In [31]:
x=np.stack((a,b),axis=1)
y=np.stack((a,b),axis=0)
print(x)
print(y)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 2 3 4]
 [1 2 3 4]]


In [30]:
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[10 10]
[2 4 6 8]


In [34]:
y=y.reshape((4,-1))
print(y)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [36]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
np.random.shuffle(a)
print(a)

[5 4 1 3 2 6 8 9 7 0]


In [39]:
a=np.random.randint(5,10,3)
print(a)

[5 7 9]


In [40]:
element=np.random.choice([1,4,3,2])
print(element)

3


STATISTICS

In [43]:
#min
a=np.array([[1,2,3,4],[7,6,2,0]])
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

0
[1 2 2 0]
[1 0]


In [44]:
#MEAN
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.125
[4.  4.  2.5 2. ]
[2.5  3.75]


In [46]:
#MEDIAN
print(np.median(a))

2.5


In [50]:
#average
w=np.array([1,2,3,4,5])
print(np.average([1,2,5,8,6],weights=w))

5.466666666666667
